Feature/news feed display
jjjangsh/dev-note pull request #5
Opened 2024-08-30 12:34 UTC by wldud7788

## What is this PR? 🔍
- **Header.jsx: ** 로그인 상태에서는 로그아웃, 마이페이지 버튼, 로그아웃 상태에서는 로그인, 회원가입 버튼 노출
- **Card.jsx:** PostContext에서 Supabase 데이터 가져오기
- **Card** 컴포넌트: 클릭 시 상세 페이지로 이동
- **styledHome.js:** Home, Header, Footer, Card의 스타일 컴포넌트 정리
- **Layout** 컴포넌트: Header, Footer 및 공통 컴포넌트를 Outlet으로 전달

## Screenshot 📸
![image](https://github.com/user-attachments/assets/616784dd-b713-4912-8a6c-b8e2efd65b39)

## Test Checklist ☑️
- [ ] Logo 클릭 시 Home 이동 확인 
- [ ] SingIn 버튼 클릭 시 Login 이동 확인
- [ ] SingOut 버튼 클릭 시 Home 이동 확인
- [ ] Mypage 버튼 클릭 시 Mypage 이동 확인
- [ ] SignUp 버튼 클릭 시 SingUp 이동 확인
## Others 👻
없습니다!

2024-08-30 12:44 UTC, jeongol commented
확인 했습니다!

2024-08-30 12:49 UTC, nninyeong reviewed
LGTM 👍 고생하셨습니당~~

2024-08-30 12:49 UTC, nninyeong commented on public/logo.png
완전 깔끔하구 예뻐요 😍

2024-08-30 12:49 UTC, nninyeong commented on src/components/Card.jsx
> +  //
안쓰는 주석 미리 지워두시면 나중에 배포할 때 편할 것 같아요!!

2024-08-30 12:49 UTC, nninyeong commented on src/components/Card.jsx
> +          <p>기술 스택이 없습니다.</p> // 기술 스택이 없을 때 메시지 표시
기술 스택 하나 이상 있는지 확인하는 유효성검사 추가하고나면 이 부분은 없애도 될 것 같습니당! 추가하면 말씀드릴게요!

2024-08-30 12:49 UTC, nninyeong commented on src/components/Header.jsx
> +  // Todo = 로그인 정보 연결
Todo 마무리됐으니 지워도 될 것 같습니당 ㅎㅎㅎ 👍👍👍

2024-08-30 12:49 UTC, nninyeong commented on src/components/Layout.jsx
짱 🙌👍👍👍

2024-08-30 12:55 UTC, kimseoyun98 commented
이뻐용 감사합니다!

2024-08-30 12:55 UTC, jeongol commented
확인했습니다 ! 고생하셨습니다!!

2024-08-30 12:58 UTC, nninyeong requested changes

2024-08-30 12:58 UTC, nninyeong commented on src/components/Card.jsx
> +          <span>사용자 이름</span>
사용자 이름도 user context에서 이제 받아올 수 있을 것 같아요!

2024-08-30 13:02 UTC, jjjangsh commented on src/components/Card.jsx
> +      <S_CardImg style={{ backgroundImage: `url(${item.thumbnail_url})` }}></S_CardImg>
여기만 inline으로 style이 들어간 이유가 궁금합니다!

2024-08-30 13:03 UTC, jjjangsh commented
LGTM😀

2024-08-30 18:08 UTC, wldud7788 commented on src/components/Card.jsx
> +      <S_CardImg style={{ backgroundImage: `url(${item.thumbnail_url})` }}></S_CardImg>
이게 Home.jsx에서 map으로 돌려서 각 해당하는 imgurl을 뿌려주는거라 인라인에 적용했는데、
스타일드 컴포넌트에서 제어하는 방법 아시면 말씀해주시면 적용하겠습니다 ： ）

2024-08-30 18:10 UTC, wldud7788 commented on src/components/Card.jsx
> +          <span>사용자 이름</span>
userContext에서는 All User가 아닌
현재 세션 정보만 받아와서
AllUser를 가져오고 포스트의 ｉｄ와 비교하는 작업이 필요해서
수정이 좀 걸릴 것 같아요~

2024-08-31 12:39 UTC, nninyeong commented on src/components/Card.jsx
> +          <span>사용자 이름</span>
아 그러네요!!! 알겠습니당!

2024-08-31 12:40 UTC, nninyeong approved these changes

2024-08-31 21:07 UTC, kimseoyun98 approved these changes

2024-08-31 21:07 UTC, kimseoyun98 commented on src/components/Card.jsx
> +const Card = ({ item }) => {
저는 post로 했는데 item변수로 하신거 확인했습니다! 현 시점에 item으로 바꿔놓는게 좋을까요?

2024-09-01 05:32 UTC, merged