Feature/detail
jjjangsh/dev-note pull request #8
Opened 2024-08-31 20:57 UTC by kimseoyun98

## What is this PR? 🔍
디테일 페이지 스타일링 및 수정 삭제 로직 구현, 연결

## Changes 📝
EditPost의 해당 id값으로 라우팅 

## Screenshot 📸
<img width="1512" alt="스크린샷 2024-09-01 오전 5 54 01" src="https://github.com/user-attachments/assets/883aa8bd-b263-48fd-a861-1ebb514c6e68">
<img width="818" alt="스크린샷 2024-09-01 오전 5 56 55" src="https://github.com/user-attachments/assets/2dcb2757-72cb-484a-987e-fe15980a6f0e">

## Test Checklist ☑️

## Others 👻

2024-09-01 06:16 UTC, nninyeong requested changes
조금.. 요청이 많아진 느낌 ㅠㅠㅠ 에러나는 필수 부분만 우선 ** 표시 해뒀습니다!!

2024-09-01 06:16 UTC, nninyeong commented on src/pages/DetailPost.jsx
> +  // user 가 특정되면 주석 풀기
detailPost는 로그인하지 않아도 접근할 수 있어서 이 부분은 제거해주셔도 될 것 같아요!

2024-09-01 06:16 UTC, nninyeong commented on src/pages/DetailPost.jsx
> +  if (posts.length === 0) return <p>로딩중...</p>;
(질문) posts.length === 0이면 Home에서 누를 수 있는 카드가 없으니까 확인하지 않아도 괜찮지 않나요?! 아니면 혹시 다른 문제가 있었나여?!

2024-09-01 06:16 UTC, nninyeong commented on src/pages/DetailPost.jsx
> +    return <p>텅!</p>;
ㅋㅋㅋㅋㅋ 여유가 되신다면 여기서 Home으로 가기 버튼이나 alert으로 일치하는 프로젝트가 없다는 거 띄우고 자동으로 home으로 넘어가는 거 추가해주셔도 좋을 것 같아여 ㅎㅎㅎㅎ

2024-09-01 06:16 UTC, nninyeong commented on src/context/PostContextProvider.jsx
> +    const { error } = await supabase.from('DEV_POSTS').delete().eq('id', id);
** supabase에서 찾아내는 조건이 id가 아니라 post_id여야해요! => .eq('post_id', id)

2024-09-01 06:16 UTC, nninyeong commented on src/pages/DetailPost.jsx
> +const GlobalStyle = createGlobalStyle`
오옹 나중에 이 부분 아예 globalStyle로 빼고 전체적으로 적용해서 메인 배경색 통일하는 거 좋을 것 같아요!

2024-09-01 06:16 UTC, nninyeong commented on src/pages/Home.jsx
> +  const { posts } = useContext(PostContext);
** Home은 지영님이 작업해두셨으니까 빼고 push하는게 좋을 것 같아요!

2024-09-01 06:23 UTC, nninyeong commented
merge하고나서 지금 접속한 유저가 detail 페이지의 post를 작성한 유저와 일치할 때만 수정/삭제 버튼 보이도록 수정하는 것 처리해야할 것 같습니다!

2024-09-01 07:27 UTC, kimseoyun98 commented on src/pages/DetailPost.jsx
> +  if (posts.length === 0) return <p>로딩중...</p>;
로딩중 구현할라고 넣어놨는데 의도한대로 되길래 남겨뒀습니다! 다른 방법이 있다면 조언 부탁드려용~

2024-09-01 07:33 UTC, kimseoyun98 commented on src/pages/DetailPost.jsx
> +    return <p>텅!</p>;
앗 ㅋㅋ 네넹 좋은 방법 같아요! 자동으로 홈화면으로 넘어가는 부분 구현하겠습니다!

2024-09-01 07:37 UTC, kimseoyun98 commented on src/pages/DetailPost.jsx
> +const GlobalStyle = createGlobalStyle`
넵 ~globalStyle.css 파일 만들어서 임포트 해놓겠습니다!

2024-09-01 07:46 UTC, kimseoyun98 commented on src/context/PostContextProvider.jsx
> +    const { error } = await supabase.from('DEV_POSTS').delete().eq('id', id);
오 그러네요! 감사합니다ㅜㅜ!

2024-09-01 07:57 UTC, kimseoyun98 commented on src/pages/DetailPost.jsx
> +  // user 가 특정되면 주석 풀기
앗 오류떠서 확인용으로 넣어둔거라 삭제해놓겠습니다~!

2024-09-01 08:13 UTC, nninyeong commented on src/pages/DetailPost.jsx
> +  if (posts.length === 0) return <p>로딩중...</p>;
우와 신기하네용 아니예요 괜찮은 것 같아요!!!

2024-09-01 08:14 UTC, nninyeong commented on src/pages/DetailPost.jsx
> +const GlobalStyle = createGlobalStyle`
오 감사합니다 ㅎㅎㅎ

2024-09-01 12:55 UTC, jjjangsh commented on src/pages/DetailPost.jsx
> +  useEffect(() => {
혹시 이 부분 useEffect로 감싸신 이유가 있으신지 궁금합니다

2024-09-01 13:22 UTC, merged

2024-09-02 03:02 UTC, kimseoyun98 commented on src/pages/DetailPost.jsx
> +  useEffect(() => {
useEffect는 한 번만 런데링되게 하려고 넣었습니다! 이것 또한 다른 좋은 방법 추천 받습니다!